# .gitea/gitea-ci.yml
name: "ORCUS SERVER DEPLOY"
on:
  push:
    branches:
      - "main"  
jobs:
  explore_gitea_actions:
    image: docker/compose:latest
    steps:
      - name: Display event info
        run: |
          echo "🎉 The job was automatically triggered by a push event."
          echo "🐧 This job is running on an Ubuntu server hosted by Gitea!"          
      
      - name: Check out repository code
        run: |
          git clone "http://10.0.0.2:3010/akiro/orcus_Server.git" orcus-server-repo
          cd orcus-server-repo
          echo "💡 The repository has been cloned to the runner."          

      - name: List files in the repository
        run: |
          cd orcus-server-repo
          ls
          echo "docker-compose.yaml should be listed above."          

      - name: Install dependencies
        run: |
          cd orcus-server-repo
          npm install
          echo "📦 Dependencies installed."
          
      # - name: Run tests
      #   run: |
      #     cd orcus-server-repo
      #     npm run jest
      #     echo "✅ Tests completed."

      - name: Start services with Docker Compose
        run: |
          cd orcus-server-repo
          docker compose down  # Stop any existing services

          export DB_NAME=${{ secrets.DB_NAME }}
          export MONGO_URL=${{ secrets.MONGO_URL }}
          export PORT=${{ secrets.PORT }}
          export JWT_ACCESS_SECRET=${{ secrets.JWT_ACCESS_SECRET }}
          export CLIENT_URL=${{ secrets.CLIENT_URL }}

          docker compose up -d --build  # Build and run services in detached mode
          echo "🚀 Your app is now running with Docker Compose!"          

      - name: Verify services are running
        run: |
          cd orcus-server-repo
          docker compose ps  # Check the status of all services
          echo "🍏 The job's status is ${{ job.status }}."          
